name: cafetroleum
description: 'An interview application'
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.5.0-152 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
 # Logic
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  # Data
  collection: ^1.18.0
  async: ^2.11.0
  throttling: ^2.0.1
  equatable: ^2.0.5
  decimal: ^3.0.2
  fpdart: ^1.1.0
  rxdart: ^0.28.0
  drift: ^2.20.0
  sqlite3: ^2.4.6
  sqlite3_flutter_libs: ^0.5.24
  path: ^1.9.0
  path_provider: ^2.1.4
  json: ^0.20.2
  # Hierarchy
  get_it: ^7.7.0
  injectable: ^2.4.4
  # Flutter expose
  auto_route: ^9.2.2
  # UI
  # Helpers
  json_annotation: ^4.9.0
  # Imported as local package because of macros experiment
  freezed: 
    path: packages/freezed-3.0.0-0.0.dev
  cached_annotation: ^1.7.0
  meta: ^1.15.0
  # extension: ^0.6.0
  intl: ^0.19.0
  # Integrations
  # Plugins
  # Stability provision

dev_dependencies:
  flutter_test:
    sdk: flutter
  analyzer: ^6.7.0
  # Code generation
  build_runner: ^2.4.12
  json_serializable: ^6.8.0
  # freezed: ^2.5.7
  injectable_generator: ^2.6.2
  cached: ^1.7.0
  drift_dev: ^2.20.1
  auto_route_generator: ^9.0.0
  # Lint
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
